herodotus:
  endpoint:
    uaa-service-name: dante-cloud-uaa
    upms-service-name: dante-cloud-upms
    gateway-service-uri: ${herodotus.environment.gateway-server-addr}
    uaa-service-uri: ${herodotus.endpoint.gateway-service-uri}/${herodotus.endpoint.uaa-service-name}
    upms-service-uri: ${herodotus.endpoint.gateway-service-uri}/${herodotus.endpoint.upms-service-name}
    access-token-uri: ${herodotus.endpoint.uaa-service-uri}/oauth2/token
    authorization-uri: ${herodotus.endpoint.uaa-service-uri}/oauth2/authorize
    token-revocation-uri: ${herodotus.endpoint.uaa-service-uri}/oauth2/revoke
    token-introspection-uri: ${herodotus.endpoint.uaa-service-uri}/oauth2/introspect
    jwk-set-uri: ${herodotus.endpoint.uaa-service-uri}/oauth2/jwks
    issuer-uri: ${herodotus.endpoint.uaa-service-uri}
    oidc-client-registration-uri: ${herodotus.endpoint.uaa-service-uri}/connect/register
    oidc-user-info-uri: ${herodotus.endpoint.uaa-service-uri}/userinfo
  swagger:
    enabled: ${herodotus.switch.swagger.enabled}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${herodotus.endpoint.issuer-uri}
          jwk-set-uri: ${herodotus.endpoint.jwk-set-uri}
        opaquetoken:
          client-id: 14a9cf797931430896ad13a6b1855611
          client-secret: a05fe1fc50ed42a4990c6c6fc4bec398
