herodotus:
  database-information:
    platform: postgresql
    driver-class-name: org.postgresql.Driver
    dialect: org.hibernate.dialect.PostgreSQL10Dialect
    url: jdbc:postgresql://${herodotus.environment.database.host}:${herodotus.environment.database.port}/${herodotus.environment.database.name}