version: "3.8"
services:
  polarismesh:
    image: polarismesh/polaris-standalone:latest
    container_name: polarismesh
    ports:
      - "15010:15010"
      - "8101:8101"
      - "8100:8100"
      - "8088:8080"
      - "8090:8090"
      - "8091:8091"
      - "8093:8093"
      - "8761:8761"
      - "9090:9090"
      - "9091:9091"

  zookeeper:
    image: debezium/zookeeper:2.6
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  kafka:
    image: debezium/kafka:2.6
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      BROKER_ID: 1
      ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: LISTENER_INNER://kafka:29092,LISTENER_OUTER://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INNER://kafka:29092,LISTENER_OUTER://192.168.101.10:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INNER:PLAINTEXT,LISTENER_OUTER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INNER
      KAFKA_ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    depends_on:
      - zookeeper

  elk:
    image: sebp/elk:latest
    container_name: elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "9300:9300"
      - "5044:5044"
    environment:
      ELASTICSEARCH_START: 1
      LOGSTASH_START: 1
      KIBANA_START: 1
      LS_HEAP_SIZE: 512m
      MAX_MAP_COUNT: 262144
      MAX_OPEN_FILES: 65536
      TZ: Asia/Shanghai
    volumes:
      - D:\\local-cached\\docker-volumes\\elk\\elasticsearch\\datas:/var/lib/elasticsearch
      - D:\\local-cached\\docker-volumes\\elk\\elasticsearch\\logs:/var/log/elasticsearch
      - D:\\local-cached\\docker-volumes\\elk\\logstash\\conf.d:/etc/logstash/conf.d