services:
  nacos:
    image: quay.io/herodotus-cloud/nacos-server:v2.4.0
    container_name: nacos
    hostname: nacos
    environment:
      MODE: standalone
#      SPRING_DATASOURCE_PLATFORM: mysql
#      MYSQL_SERVICE_HOST: 192.168.101.10
#      MYSQL_SERVICE_PORT: 13306
#      MYSQL_SERVICE_USER: nacos
#      MYSQL_SERVICE_PASSWORD: nacos
#      MYSQL_SERVICE_DB_NAME: nacos
#      MYSQL_SERVICE_DB_PARAM: characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
      SPRING_DATASOURCE_PLATFORM: postgresql
      POSTGRESQL_SERVICE_HOST: 192.168.101.10
      POSTGRESQL_SERVICE_PORT: 15432
      POSTGRESQL_SERVICE_USER: nacos
      POSTGRESQL_SERVICE_PASSWORD: nacos
      POSTGRESQL_SERVICE_DB_NAME: nacos
      POSTGRESQL_SERVICE_DB_PARAM: tcpKeepAlive=true&reWriteBatchedInserts=true&ApplicationName=nacos
      NACOS_AUTH_IDENTITY_KEY: serverIdentity
      NACOS_AUTH_IDENTITY_VALUE: security
      NACOS_AUTH_TOKEN: SecretKey012345678901234567890123456789012345678901234567890123456789
    volumes:
      - /usr/local/docker-volumes/nacos/data:/home/nacos/data
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"

  kafka:
    image: quay.io/herodotus-cloud/kafka:3.7.1
    container_name: kafka
    hostname: broker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://192.168.101.10:9092,PLAINTEXT://broker:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  elk:
    image: sebp/elk:latest
    container_name: elk
    hostname: elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "9300:9300"
      - "5044:5044"
    environment:
      ELASTICSEARCH_START: 1
      LOGSTASH_START: 1
      KIBANA_START: 1
      LS_HEAP_SIZE: 512m
      MAX_MAP_COUNT: 262144
      MAX_OPEN_FILES: 65536
      TZ: Asia/Shanghai
    volumes:
      - /usr/local/docker-volumes/elk/elasticsearch/data:/var/lib/elasticsearch
      - /usr/local/docker-volumes/elk/elasticsearch/logs:/var/log/elasticsearch
      - /usr/local/docker-volumes/elk/logstash/conf.d:/etc/logstash/conf.d

  sentinel:
    image: quay.io/herodotus-cloud/sentinel-dashboard:v1.8.8
    container_name: sentinel-dashboard
    environment:
      SENTINEL_ADMIN_USERNAME: sentinel
      SENTINEL_ADMIN_PASSWORD: sentinel
    ports:
      - "8858:8858"